import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import CartStoreProvider from "@/components/store/cartStore";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartStoreProvider>
          <Navbar />
          {children}
        </CartStoreProvider>
      </body>
    </html>
  );
}
